---
abstract: 'Perl interface to the 3.x series of the gtk+ toolkit'
author:
  - 'Torsten Schoenfeld <kaffeetisch@gmx.de>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Gtk3
requires:
  Cairo::GObject: '1.000'
  Carp: '0'
  Exporter: '0'
  Glib::Object::Introspection: '0.043'
  Test::Simple: '0.96'
resources:
  IRC: irc://irc.gimp.org/#gtk-perl
  Twitter: https://twitter.com/GTKPerl
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Gtk3
  homepage: http://gtk2-perl.sourceforge.net
  repository: git://git.gnome.org/perl-Gtk3
version: '0.038'
x_generated_by_perl: v5.28.1
x_serialization_backend: 'YAML::Tiny version 1.73'
